FlexGridSizer changed signature
Traceback (most recent call last):
  File "bash\bash.py", line 193, in main
    _main(opts)
  File "bash\bash.py", line 371, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4038, in Init
    frame.RefreshData(booting=True)
  File "bash\balt.py", line 1623, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\__init__.py", line 3819, in RefreshData
    self.warn_corrupted()
  File "bash\basher\__init__.py", line 3901, in warn_corrupted
    message, liststyle='list', canCancel=False)
  File "bash\balt.py", line 1047, in Display
    with cls(*args, **kwargs) as dialog:
  File "bash\balt.py", line 2809, in __init__
    sizer = wx.FlexGridSizer(len(lists) + 2, 1)
TypeError: FlexGridSizer(): arguments did not match any overloaded call:
  overload 1: not enough arguments
  overload 2: argument 2 has unexpected type 'int'
  overload 3: not enough arguments
  overload 4: not enough arguments