Move record constants out of bush WIP: EEE RRR
Note I removed virtually unused params of getEffectsSummary(self):
getSpellSchool(self): to reduce globals (mgef_school and co) occurrences
Mopy/bash/cint.py: actorValues -> ActorValues

Note MreHasEffects.getEffectsSummary indent was broken:

Mopy/bash/game/skyrim/records.py:
for loop out of with as was return - would raise
ValueError: I/O operation on closed file. getEffectsSummary is used
exclusively in Saves Oblivion only code that's why we never saw this

Mopy/bash/game/fallout3/records.py:
Mopy/bash/game/oblivion/records.py:
return inside loop

The oblivion one broke in 52515a8ec586844d043ed636d3f260a28b969d1f

WIP - TODOs:

- mgef_school and co per game? Probably now used in Oblivion only
patcher/parser code
- related to above - move some of it to `game/` package? We do not want
that package to bloat ofc but constants do belong there
- `game_mod` should be absorbed to the `game` instance - its uses point
to hacky/tricky parts of the code

This brings to light a design bug - MreHasEffects being an old style
class breaks the `__slots__` pattern. But fixing is not easy cause:

@@ -2196,5 +2196,5 @@ def mapFids(self,record,function,save=False):
 #------------------------------------------------------------------------------
-class MreHasEffects(object):
+class MreHasEffects: #(object): # this alone doesn't break MreSpel
     """Mixin class for magic items."""
-    __slots__ = []
+    ##: __slots__ = [] # MreSpel.flags should be renamed to _flags

breaks MreSpel as in:

Error in Oblivion.esm
parsers.py 3994 load:
Traceback (most recent call last):
  File "bash\parsers.py", line 3988, in load
    self.tops[label].load(ins, do_unpack and (topClass != MobBase))
  File "bash\record_groups.py", line 84, in load
    ins.tell() + self.size - self.header.__class__.rec_header_size)
  File "bash\record_groups.py", line 186, in loadData
    record = recClass(header,ins,True)
  File "bash\brec.py", line 1690, in __init__
    self.__class__.melSet.initRecord(self, header, ins, do_unpack)
  File "bash\brec.py", line 1234, in initRecord
    element.setDefault(record)
  File "bash\brec.py", line 977, in setDefault
    setter(attr,value)
AttributeError: 'MreSpel' object attribute 'flags' is read-only

The MreHasEffect would add to the slots `'flags`' and this confuses
python descriptors - go figure, coffee is wearing out in the words of
D. Beazley.

class MreRecord(object):
    __slots__ = []

class MreHasEffects(object): # this alone doesn't break MreSpel
    """Mixin class for magic items."""
    ##: __slots__ = [] # MreSpel.flags should be renamed to _flags

class MreSpel(MreRecord, MreHasEffects):
    flags = 'class variable'
    __slots__ = ('flags', )

    # def __init__(self, flags='instance_var'):
    #     self.flags = flags

spell = MreSpel()
print (spell.flags)
spell.flags = 'set'
spell.flags1 = 'set'
print (spell.flags)
print (spell.__class__.flags)

Used in some of the MreRecord subclassses here - I guess I need to
define __slots__ in MI too (MI with an old style class ?)

Situation is made worse due to `flags` identifier being used all over.
The (unfortunate) pattern used in Bash is (as far as I understand)
define a `_flags` class variable that is then added to the slots via
the melSet as `flags`. Sometimes the class variable comes with more
descriptive names as `game.skyrim.records.MreSpel.SpelTypeFlags`,
which is added to the `_slots__` as `dataFlags` this time around.

Under game handling