SyntaxError: import * is not allowed in function 'init': so SSE blows
Wrye Bash starting
Using Wrye Bash Version 307
OS info: Windows-7-6.1.7601-SP1
Python version: 2.7.12
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: UTF8; output encoding: None; locale: ('en_US', 'cp1253')
filesystem encoding: mbcs
Searching for game to manage:
C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\game\skyrimse\__init__.py:269: SyntaxWarning: import * only allowed at module level
  def init():
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    main.main()
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\main.py", line 323, in main
    ret = bush.setGame(opts.gameName, opts.oblivionPath, bashIni)
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bush.py", line 164, in setGame
    foundGames_, name = _detectGames(workingDir, bashIni)
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bush.py", line 96, in _detectGames
    foundGames_ = _supportedGames() # sets _allGames if not set
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\bush.py", line 59, in _supportedGames
    module = __import__('game',globals(),locals(),[modname],-1)
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\game\skyrimse\__init__.py", line 276
    from .constants import *
SyntaxError: import * is not allowed in function 'init' because it contains a nested function with free variables